version: '3'
services:

  ecom-postgres:
    image: "postgres:9.6-alpine"
    container_name: icinuser-postgres
    volumes:
      - ecom-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB:ecom
      - POSTGRES_USER:ecom
      - POSTGRES_PASSWORD:ecom

  ecom-app:
    build: ./icin-user
    container_name: icin-user
    environment:
      - DB_SERVER=icinuser-postgres
    ports:
      - 8081:8081
    links:
      - icinuser-postgres

  ecom-ui:
    image: "angular-alpine:0.0.1"
          container_name: ecom-ui 
          tty: true
          stdin_open: true
          networks:
            app_net:
            ipv4_address: 172.16.238.05
          depends_on:
            - icin-user


volumes:
  ecom-data:
  
networks:
        app_net:
          driver: bridge
        ipam:
        driver: default
        config:
          - subnet: 172.16.238.0/24
